<a href="https://colab.research.google.com/github/praut05/Github/blob/main/Standardization_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')

In [ ]:
df.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [ ]:
df = df.iloc[:,2:]
df.sample(10)

,Age,EstimatedSalary,Purchased
127,26,32000,0
362,47,50000,1
194,28,89000,0
249,35,97000,1
198,26,80000,0
142,35,59000,0
213,35,58000,0
96,35,25000,0
113,37,55000,0
282,37,70000,1


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop('Purchased',axis=1),
                                                 df['Purchased'],
                                                 test_size=0.3,
                                                 random_state=0)
X_train.shape,X_test.shape

((280, 2), (120, 2))

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# fit the scaler to train set, it will learn the parameters
scaler.fit(X_train)

# transform train and test sets
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
scaler.mean_

array([3.78642857e+01, 6.98071429e+04])

In [ ]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [ ]:
X_train_scaled

,Age,EstimatedSalary
0,-1.163172,-1.584970
1,2.170181,0.930987
2,0.013305,1.220177
3,0.209385,1.075582
4,0.405465,-0.486047
...,...,...
275,0.993704,-1.151185
276,-0.869053,-0.775237
277,-0.182774,-0.514966
278,-1.065133,-0.457127


In [ ]:
np.round(X_train.describe(),1)

,Age,EstimatedSalary
count,280.0,280.0
mean,37.9,69807.1
std,10.2,34641.2
min,18.0,15000.0
25%,30.0,43000.0
50%,37.0,70500.0
75%,46.0,88000.0
max,60.0,150000.0


In [ ]:
np.round(X_train_scaled.describe(),1)

,Age,EstimatedSalary
count,280.0,280.0
mean,0.0,0.0
std,1.0,1.0
min,-1.9,-1.6
25%,-0.8,-0.8
50%,-0.1,0.0
75%,0.8,0.5
max,2.2,2.3


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()
lr_scaled = LogisticRegression()

In [ ]:
lr.fit(X_train,y_train)
lr_scaled.fit(X_train_scaled,y_train)


LogisticRegression()

In [ ]:
y_pred = lr.predict(X_test)
y_pred_scaled = lr_scaled.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("Actual",accuracy_score(y_test,y_pred))
print("Scaled",accuracy_score(y_test,y_pred_scaled))


Actual 0.875
Scaled 0.8666666666666667


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt = DecisionTreeClassifier()
dt_scaled = DecisionTreeClassifier()

In [ ]:
dt.fit(X_train,y_train)
dt_scaled.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = dt.predict(X_test)
y_pred_scaled = dt_scaled.predict(X_test_scaled)

In [ ]:
print("Actual",accuracy_score(y_test,y_pred))
print("Scaled",accuracy_score(y_test,y_pred_scaled))

Actual 0.875
Scaled 0.8666666666666667


In [ ]:
df = pd.read_csv('wine_data.csv', header = None,usecols=[0,1,2])
df.columns=['Class label','Alcohol','Malic acid']

In [ ]:
df.head()

,Class label,Alcohol,Malic acid
0,1,14.23,1.71
1,1,13.20,1.78
2,1,13.16,2.36
3,1,14.37,1.95
4,1,13.24,2.59


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(10)

,age,gender,review,education,purchased
22,18,Female,Poor,PG,Yes
41,23,Male,Good,PG,Yes
7,60,Female,Poor,School,Yes
14,15,Male,Poor,PG,Yes
19,97,Male,Poor,PG,Yes
20,57,Female,Average,School,Yes
32,92,Male,Average,UG,Yes
6,18,Male,Good,School,No
42,30,Female,Good,PG,Yes
39,76,Male,Poor,PG,No


In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.sample(10)

,review,education,purchased
31,Poor,School,Yes
4,Average,UG,No
24,Average,PG,Yes
12,Poor,School,No
32,Average,UG,Yes
46,Poor,PG,No
29,Average,UG,Yes
37,Average,PG,Yes
3,Good,PG,No
18,Good,School,No


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [ ]:
X_train

,review,education
36,Good,UG
28,Poor,School
24,Average,PG
10,Good,UG
43,Poor,PG
33,Good,PG
9,Good,UG
44,Average,UG
0,Average,School
47,Good,PG


In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [ ]:
X_train

array([[2., 1.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.]])

In [ ]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [ ]:
from sklearn.preprocessing import LabelEncoder

This transformer should be used to encode target values, i.e. y, and not the input X.

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0])